### ISSUE TITLE
Including schema in connections class & create table syntax

### ISSUE THREAD

**Issue by eleanorsk-innovisk** [gigisr/data_etl#27]
Work around is to include the schema in table_name object '[scheme].table_name'.

This causes issues when creating the temp table as SQL server won't read #Temp[scheme].table_name as a table name.

Must also include table structure when creating a table in SQL server, hence best to use select * into newtable from oldtable. 

Insert values must had "[" not "'"

Variables updated as follows:
```
var_sql = (f"Drop table if exists #Temp "
                f"SELECT Top(0) * into #Temp FROM {dict_cnx['table_name']};")
cursor.execute(var_sql)
cnx.commit()

var_sql_template = "INSERT INTO #Temp ([{}]) VALUES {}".format(
    "{}".format("], [".join(table.columns.tolist())),
    '{}'
)
```

**Comment by gigisr** [comment]
Fixed in branch fix-issues! Thanks for raising :)
